# Generated by Django 2.2.6 on 2019-11-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Python', 'Python'), ('Django', 'Django'), ('AI', 'AI'), ('Analytics', 'Analytics'), ('DS', 'DS'), ('Science', 'Science'), ('Technology', 'Technology'), ('Literature', 'Literature'), ('Art', 'Art'), ('Ethics', 'Ethics'), ('Economics', 'Economics'), ('Finance', 'Finance')], default='general', max_length=20),
        ),
    ]
